# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Has_OpenMP <- function() {
    .Call(`_SpliceWiz_Has_OpenMP`)
}

Test_OpenMP_For <- function() {
    .Call(`_SpliceWiz_Test_OpenMP_For`)
}

c_Check_Cov <- function(s_in) {
    .Call(`_SpliceWiz_c_Check_Cov`, s_in)
}

c_RLE_From_Cov <- function(s_in, seqname, start, end, strand) {
    .Call(`_SpliceWiz_c_RLE_From_Cov`, s_in, seqname, start, end, strand)
}

c_Cov_Seqnames <- function(s_in) {
    .Call(`_SpliceWiz_c_Cov_Seqnames`, s_in)
}

c_RLEList_From_Cov <- function(s_in, strand) {
    .Call(`_SpliceWiz_c_RLEList_From_Cov`, s_in, strand)
}

c_gunzip_DF <- function(s_in, s_header_begin) {
    .Call(`_SpliceWiz_c_gunzip_DF`, s_in, s_header_begin)
}

c_gunzip <- function(s_in, s_out) {
    .Call(`_SpliceWiz_c_gunzip`, s_in, s_out)
}

SpliceWizMain <- function(bam_file, reference_file, output_file, verbose, n_threads, multiRead) {
    .Call(`_SpliceWiz_SpliceWizMain`, bam_file, reference_file, output_file, verbose, n_threads, multiRead)
}

SpliceWizMain_multi <- function(reference_file, bam_files, output_files, max_threads, verbose, multiRead) {
    .Call(`_SpliceWiz_SpliceWizMain_multi`, reference_file, bam_files, output_files, max_threads, verbose, multiRead)
}

c_GenerateMappabilityReads <- function(genome_file, out_fa, read_len, read_stride, error_pos) {
    .Call(`_SpliceWiz_c_GenerateMappabilityReads`, genome_file, out_fa, read_len, read_stride, error_pos)
}

c_GenerateMappabilityRegions <- function(bam_file, output_file, threshold, includeCov, verbose, n_threads) {
    .Call(`_SpliceWiz_c_GenerateMappabilityRegions`, bam_file, output_file, threshold, includeCov, verbose, n_threads)
}

c_BAM2COV <- function(bam_file, output_file, verbose, n_threads, multiRead) {
    .Call(`_SpliceWiz_c_BAM2COV`, bam_file, output_file, verbose, n_threads, multiRead)
}

c_doStats <- function(bam_file, output_file, verbose, n_threads, multiRead) {
    .Call(`_SpliceWiz_c_doStats`, bam_file, output_file, verbose, n_threads, multiRead)
}

